In [1]:
import numpy as np

In [2]:
# Sort,Search and Counting Functions

In [3]:
arr = np.array([2,3,4,5,6])

In [4]:
arr

array([2, 3, 4, 5, 6])

In [5]:
arr1 = np.array([4,5,3,2,9,8,6,7])

In [6]:
arr1

array([4, 5, 3, 2, 9, 8, 6, 7])

In [7]:
np.sort(arr1)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.searchsorted(arr1,10)
# Find indices where elements should be inserted to maintain order.

8

In [15]:
arr = np.array([0,324,625,65,6,6,0,0,0,234])

In [16]:
np.count_nonzero(arr)

6

In [18]:
np.where(arr>0)

(array([1, 2, 3, 4, 5, 9], dtype=int64),)

In [21]:
np.extract(arr>2,arr)

array([324, 625,  65,   6,   6, 234])

In [22]:
# Numpy --> Byte Swapping

In [23]:
arr

array([  0, 324, 625,  65,   6,   6,   0,   0,   0, 234])

In [27]:
arr.byteswap() # arr.byteswap(True) == inplace = True

array([         0, 1140916224, 1895956480, 1090519040,  100663296,
        100663296,          0,          0,          0, -369098752])

In [28]:
# Numpy --> Copies and Views

In [29]:
arr

array([  0, 324, 625,  65,   6,   6,   0,   0,   0, 234])

In [30]:
a = np.copy(arr) # '.copy()' creates a deep copy

In [31]:
a

array([  0, 324, 625,  65,   6,   6,   0,   0,   0, 234])

In [32]:
arr[0] = 100

In [33]:
arr

array([100, 324, 625,  65,   6,   6,   0,   0,   0, 234])

In [34]:
a

array([  0, 324, 625,  65,   6,   6,   0,   0,   0, 234])

In [35]:
b = arr.view() # creates a swallow copy i.e. if we change anythin in 'b' then that will also be changed in 'arr'

In [36]:
b

array([100, 324, 625,  65,   6,   6,   0,   0,   0, 234])

In [37]:
b[0] = 123

In [38]:
b

array([123, 324, 625,  65,   6,   6,   0,   0,   0, 234])

In [39]:
arr

array([123, 324, 625,  65,   6,   6,   0,   0,   0, 234])

In [40]:
# Numpy --> Matrix Library

In [41]:
import numpy.matlib as nm
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [42]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [43]:
type(nm.ones((3,4)))

numpy.matrix

In [44]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [45]:
## Numpy --> Linear Algebra

In [46]:
arr1

array([4, 5, 3, 2, 9, 8, 6, 7])

In [47]:
arr1 = np.random.randint([[2,3],[4,5]])
arr2 = np.random.randint([[5,6],[3,4]])

In [48]:
arr1

array([[0, 2],
       [1, 3]])

In [49]:
arr2

array([[0, 2],
       [2, 2]])

In [50]:
np.dot(arr1,arr2)

array([[4, 4],
       [6, 8]])

In [51]:
arr1@arr2

array([[4, 4],
       [6, 8]])

In [52]:
# dot product == matrix multiplication 