In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5]


In [5]:
arr = np.array(l)

In [6]:
type(arr)

numpy.ndarray

In [7]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [9]:
arr1 = np.array([[1,2,3],[2,3,4]])

In [10]:
arr.ndim

1

In [11]:
arr1.ndim

2

In [12]:
arr

array([1, 2, 3, 4, 5])

In [13]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [15]:
mat=np.matrix(l)

In [16]:
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [17]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4, 5]])

In [18]:
arr

array([1, 2, 3, 4, 5])

In [19]:
a = arr

In [20]:
a

array([1, 2, 3, 4, 5])

In [21]:
arr

array([1, 2, 3, 4, 5])

In [22]:
arr[0]

1

In [23]:
arr[0] = 100

In [24]:
arr

array([100,   2,   3,   4,   5])

In [25]:
a

array([100,   2,   3,   4,   5])

In [26]:
# a = arr
#This is known as swallow copy operation

In [27]:
b = arr.copy() # b = np.copy(arr)

In [28]:
b

array([100,   2,   3,   4,   5])

In [29]:
arr

array([100,   2,   3,   4,   5])

In [30]:
arr[0] = 1

In [31]:
arr

array([1, 2, 3, 4, 5])

In [32]:
b

array([100,   2,   3,   4,   5])

In [33]:
np.fromfunction(lambda i,j : i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [35]:
np.fromfunction(lambda i,j : i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [37]:
list(i*i for i in range(5))

[0, 1, 4, 9, 16]

In [45]:
iterable = (i*i for i in range(5))

In [46]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [47]:
np.fromstring('23 45 67',sep=' ')

array([23., 45., 67.])

In [48]:
np.fromstring('23,45,67',sep=',')

array([23., 45., 67.])

In [49]:
arr 

array([1, 2, 3, 4, 5])

In [50]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [51]:
arr.ndim

1

In [52]:
arr1.ndim

2

In [53]:
# [[]] --> 2 dimensional because there are two square brackets that are open and closed

In [54]:
arr.size

5

In [55]:
arr1.size # returns total no. of elements

6

In [56]:
arr.shape # 1 dimensional, 5 columns

(5,)

In [57]:
arr1.shape # 2 rows and 3 columns

(2, 3)

In [58]:
arr.dtype

dtype('int32')

In [59]:
arr1.dtype

dtype('int32')