In [1]:
import numpy as np

In [2]:
list(range(5))

[0, 1, 2, 3, 4]

In [3]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
list(range(0.4,10.4))

TypeError: 'float' object cannot be interpreted as an integer

In [5]:
# range function always takes a range of integers not a floating point numbers 

In [6]:
np.arange(.4,10.4)

array([0.4, 1.4, 2.4, 3.4, 4.4, 5.4, 6.4, 7.4, 8.4, 9.4])

In [7]:
# In numpy, we have a arange function which will also take range in a floating point and generates the data accordingly

In [8]:
np.arange(.4,10.4,0.2)

array([ 0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,  2.4,
        2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,  4.6,
        4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,  6.8,
        7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,  9. ,
        9.2,  9.4,  9.6,  9.8, 10. , 10.2])

In [9]:
list(np.arange(.4,10.4,0.2))

[0.4,
 0.6000000000000001,
 0.8000000000000002,
 1.0000000000000002,
 1.2000000000000002,
 1.4000000000000004,
 1.6000000000000005,
 1.8000000000000003,
 2.0000000000000004,
 2.2000000000000006,
 2.400000000000001,
 2.6000000000000005,
 2.8000000000000007,
 3.000000000000001,
 3.2000000000000006,
 3.400000000000001,
 3.600000000000001,
 3.800000000000001,
 4.000000000000002,
 4.200000000000001,
 4.400000000000002,
 4.600000000000001,
 4.800000000000002,
 5.000000000000002,
 5.200000000000002,
 5.400000000000002,
 5.600000000000002,
 5.8000000000000025,
 6.000000000000002,
 6.200000000000002,
 6.400000000000002,
 6.600000000000002,
 6.8000000000000025,
 7.000000000000003,
 7.200000000000003,
 7.400000000000003,
 7.600000000000003,
 7.8000000000000025,
 8.000000000000002,
 8.200000000000003,
 8.400000000000004,
 8.600000000000003,
 8.800000000000002,
 9.000000000000004,
 9.200000000000003,
 9.400000000000004,
 9.600000000000003,
 9.800000000000004,
 10.000000000000004,
 10.20000000000000

In [10]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [12]:
np.logspace(1,5,10,base=10) # by default base=10

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [14]:
np.logspace(1,5,10,base=3)

array([  3.        ,   4.88849467,   7.96579337,  12.98024613,
        21.151288  ,  34.46598619,  56.16226322,  91.51630808,
       149.12566131, 243.        ])

In [16]:
np.logspace(1,5,10,base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.zeros((3,4,2)) # will generate 4x2 array of 3 size

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [20]:
np.zeros((3,4,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [21]:
# More than 3 dimensions you will not be able to visualize but you will be able to create that data

In [22]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [24]:
arr2 = np.ones((3,4))

In [25]:
arr2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
arr2+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [27]:
arr2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
arr2*5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [30]:
np.empty((3,4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [31]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [32]:
np.empty(4)

array([2.12199579e-314, 1.25834350e-311, 6.50190390e-321, 3.79442416e-321])

In [34]:
np.eye(5) # Identity matrix,here no.of rows == no.of columns

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
import pandas as pd
pd.DataFrameFrame(arr2)

0    1    2    3
0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0

In [36]:
np.random.rand(2,3)

array([[0.92094254, 0.892253  , 0.21266009],
       [0.53968555, 0.32855467, 0.2437241 ]])

In [37]:
np.random.rand((2,3))

TypeError: 'tuple' object cannot be interpreted as an integer

In [40]:
np.random.randn(2,3) # randn will generate the data whose data is being generated on std. normal distribution,i.e. mean=0 and std=1

array([[ 0.23477137,  0.34196444, -1.73385162],
       [ 1.44433876,  0.27500699,  0.36074163]])

In [39]:
np.random.randint(2,3)

2

In [42]:
arr3 = np.random.randint(1,5,(3,4))

In [43]:
arr2.size

12

In [45]:
arr3.shape

(3, 4)

In [46]:
arr3.reshape(4,3)

array([[2, 2, 2],
       [4, 4, 1],
       [3, 2, 3],
       [1, 4, 4]])

In [47]:
arr3.reshape(6,2)

array([[2, 2],
       [2, 4],
       [4, 1],
       [3, 2],
       [3, 1],
       [4, 4]])

In [48]:
arr3.reshape(2,6)

array([[2, 2, 2, 4, 4, 1],
       [3, 2, 3, 1, 4, 4]])

In [49]:
arr1 = np.random.randint(1,10,(5,6))

In [50]:
arr1

array([[7, 9, 4, 9, 4, 8],
       [3, 4, 3, 6, 8, 9],
       [6, 6, 4, 5, 6, 1],
       [7, 1, 4, 5, 2, 3],
       [7, 8, 9, 5, 8, 6]])

In [51]:
arr1>8

array([[False,  True, False,  True, False, False],
       [False, False, False, False, False,  True],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False,  True, False, False, False]])

In [52]:
arr1[arr1>8]

array([9, 9, 9, 9])

In [53]:
arr1[0,[0,1]]

array([7, 9])

In [58]:
arr1[1:3,[3,4]]

array([[6, 8],
       [5, 6]])

In [60]:
arr1 = np.random.randint(1,5,(3,3))
arr2 = np.random.randint(1,5,(3,3))

In [61]:
arr1

array([[1, 1, 4],
       [1, 4, 3],
       [4, 3, 2]])

In [62]:
arr2

array([[1, 2, 4],
       [2, 4, 4],
       [3, 2, 2]])

In [63]:
arr1+arr2
# This will perform addition of indices

array([[2, 3, 8],
       [3, 8, 7],
       [7, 5, 4]])

In [64]:
arr1-arr2

array([[ 0, -1,  0],
       [-1,  0, -1],
       [ 1,  1,  0]])

In [65]:
arr1*arr2

array([[ 1,  2, 16],
       [ 2, 16, 12],
       [12,  6,  4]])

In [66]:
arr1/arr2

array([[1.        , 0.5       , 1.        ],
       [0.5       , 1.        , 0.75      ],
       [1.33333333, 1.5       , 1.        ]])

In [67]:
arr1@arr2 # Matrix multiplication

array([[15, 14, 16],
       [18, 24, 26],
       [16, 24, 32]])

In [68]:
arr1/0

C:\Users\yashg\AppData\Local\Temp\ipykernel_22952\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [69]:
## Numpy Broadcasting
arr = np.zeros((3,4))

In [70]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [71]:
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [72]:
arr+5
# In the above example, we have added 5 in arr, so it has been added in every element and it is known as broadcasting

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [78]:
a = np.array([1,2,3,4])

In [79]:
a

array([1, 2, 3, 4])

In [80]:
arr+a # column-wise addition

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [83]:
b = np.array([[3,4,5]])

In [86]:
arr1 = arr+b.T # row-wise addition

In [85]:
b.T

array([[3],
       [4],
       [5]])

In [87]:
arr1

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [88]:
np.sqrt(arr1)

array([[1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [2.        , 2.        , 2.        , 2.        ],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798]])

In [89]:
np.log10(arr1)

array([[0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999],
       [0.69897   , 0.69897   , 0.69897   , 0.69897   ]])

In [90]:
np.exp(arr1)

array([[ 20.08553692,  20.08553692,  20.08553692,  20.08553692],
       [ 54.59815003,  54.59815003,  54.59815003,  54.59815003],
       [148.4131591 , 148.4131591 , 148.4131591 , 148.4131591 ]])

In [91]:
np.min(arr1)

3.0

In [92]:
np.max(arr1)

5.0