In [1]:
import numpy as np

In [2]:
# Numpy - Array Manipulation

In [3]:
arr = np.random.randint(1,10,(4,4))

In [9]:
arr

array([[4, 9, 1, 9],
       [2, 3, 1, 5],
       [2, 3, 3, 1],
       [7, 1, 2, 9]])

In [10]:
arr.reshape(2,8)

array([[4, 9, 1, 9, 2, 3, 1, 5],
       [2, 3, 3, 1, 7, 1, 2, 9]])

In [11]:
arr

array([[4, 9, 1, 9],
       [2, 3, 1, 5],
       [2, 3, 3, 1],
       [7, 1, 2, 9]])

In [12]:
arr.T

array([[4, 2, 2, 7],
       [9, 3, 3, 1],
       [1, 1, 3, 2],
       [9, 5, 1, 9]])

In [13]:
arr.flatten() # Creates one dimensional array

array([4, 9, 1, 9, 2, 3, 1, 5, 2, 3, 3, 1, 7, 1, 2, 9])

In [14]:
arr

array([[4, 9, 1, 9],
       [2, 3, 1, 5],
       [2, 3, 3, 1],
       [7, 1, 2, 9]])

In [15]:
np.expand_dims(arr,axis=1)

array([[[4, 9, 1, 9]],

       [[2, 3, 1, 5]],

       [[2, 3, 3, 1]],

       [[7, 1, 2, 9]]])

In [16]:
np.expand_dims(arr,axis=0)

array([[[4, 9, 1, 9],
        [2, 3, 1, 5],
        [2, 3, 3, 1],
        [7, 1, 2, 9]]])

In [17]:
data = np.array([[1],[2],[3]])

In [18]:
data

array([[1],
       [2],
       [3]])

In [19]:
np.squeeze(data)

array([1, 2, 3])

In [20]:
np.repeat(data,2)

array([1, 1, 2, 2, 3, 3])

In [21]:
np.repeat(arr,2) # repeat returns 1 dimensional array of any type of array

array([4, 4, 9, 9, 1, 1, 9, 9, 2, 2, 3, 3, 1, 1, 5, 5, 2, 2, 3, 3, 3, 3,
       1, 1, 7, 7, 1, 1, 2, 2, 9, 9])

In [22]:
arr

array([[4, 9, 1, 9],
       [2, 3, 1, 5],
       [2, 3, 3, 1],
       [7, 1, 2, 9]])

In [26]:
np.roll(data,2) # roll==shift

array([[2],
       [3],
       [1]])

In [27]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [28]:
# Numpy - Binary Operators

In [29]:
arr1 = np.random.randint(1,10,(3,4))
arr2 = np.random.randint(1,10,(3,4))

In [30]:
arr1

array([[6, 6, 3, 3],
       [7, 3, 1, 6],
       [9, 7, 4, 9]])

In [31]:
arr2

array([[1, 2, 8, 6],
       [9, 5, 4, 6],
       [2, 7, 1, 8]])

In [32]:
arr1+arr2

array([[ 7,  8, 11,  9],
       [16,  8,  5, 12],
       [11, 14,  5, 17]])

In [34]:
arr1-arr2

array([[ 5,  4, -5, -3],
       [-2, -2, -3,  0],
       [ 7,  0,  3,  1]])

In [35]:
arr1*arr2

array([[ 6, 12, 24, 18],
       [63, 15,  4, 36],
       [18, 49,  4, 72]])

In [36]:
arr1/arr2

array([[6.        , 3.        , 0.375     , 0.5       ],
       [0.77777778, 0.6       , 0.25      , 1.        ],
       [4.5       , 1.        , 4.        , 1.125     ]])

In [37]:
arr1@arr2

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [38]:
arr1**arr2

array([[       6,       36,     6561,      729],
       [40353607,      243,        1,    46656],
       [      81,   823543,        4, 43046721]])

In [39]:
~arr1

array([[ -7,  -7,  -4,  -4],
       [ -8,  -4,  -2,  -7],
       [-10,  -8,  -5, -10]])

In [40]:
arr1>arr2

array([[ True,  True, False, False],
       [False, False, False, False],
       [ True, False,  True,  True]])

In [41]:
arr1[arr1>arr2]

array([6, 6, 9, 4, 9])

In [42]:
# Numpy --> String Functions

In [43]:
arr = np.array(['pw','skills'])

In [44]:
arr

array(['pw', 'skills'], dtype='<U6')

In [45]:
np.char.upper(arr)

array(['PW', 'SKILLS'], dtype='<U6')

In [46]:
np.char.capitalize(arr)

array(['Pw', 'Skills'], dtype='<U6')

In [47]:
np.char.title(arr)

array(['Pw', 'Skills'], dtype='<U6')

In [48]:
# Numpy - Mathematical Functions

In [49]:
arr1

array([[6, 6, 3, 3],
       [7, 3, 1, 6],
       [9, 7, 4, 9]])

In [50]:
np.sin(arr1)

array([[-0.2794155 , -0.2794155 ,  0.14112001,  0.14112001],
       [ 0.6569866 ,  0.14112001,  0.84147098, -0.2794155 ],
       [ 0.41211849,  0.6569866 , -0.7568025 ,  0.41211849]])

In [51]:
np.cos(arr1)

array([[ 0.96017029,  0.96017029, -0.9899925 , -0.9899925 ],
       [ 0.75390225, -0.9899925 ,  0.54030231,  0.96017029],
       [-0.91113026,  0.75390225, -0.65364362, -0.91113026]])

In [52]:
np.tan(arr1)

array([[-0.29100619, -0.29100619, -0.14254654, -0.14254654],
       [ 0.87144798, -0.14254654,  1.55740772, -0.29100619],
       [-0.45231566,  0.87144798,  1.15782128, -0.45231566]])

In [53]:
np.cot(arr1)

AttributeError: module 'numpy' has no attribute 'cot'

In [54]:
np.sin([1])

array([0.84147098])

In [56]:
np.log10(arr1)

array([[0.77815125, 0.77815125, 0.47712125, 0.47712125],
       [0.84509804, 0.47712125, 0.        , 0.77815125],
       [0.95424251, 0.84509804, 0.60205999, 0.95424251]])

In [57]:
np.exp(arr1)

array([[4.03428793e+02, 4.03428793e+02, 2.00855369e+01, 2.00855369e+01],
       [1.09663316e+03, 2.00855369e+01, 2.71828183e+00, 4.03428793e+02],
       [8.10308393e+03, 1.09663316e+03, 5.45981500e+01, 8.10308393e+03]])

In [58]:
np.power(arr1,2)

array([[36, 36,  9,  9],
       [49,  9,  1, 36],
       [81, 49, 16, 81]], dtype=int32)

In [60]:
np.mean(arr1)

5.333333333333333

In [62]:
np.median(arr1)

6.0

In [66]:
arr1

array([[6, 6, 3, 3],
       [7, 3, 1, 6],
       [9, 7, 4, 9]])

In [67]:
np.std(arr1)

2.4267032964268394

In [68]:
np.var(arr1)

5.888888888888888

In [69]:
np.min(arr1)

1

In [70]:
np.max(arr1)

9

In [71]:
# Numpy --> Arithmetic Operations

In [72]:
arr1

array([[6, 6, 3, 3],
       [7, 3, 1, 6],
       [9, 7, 4, 9]])

In [73]:
arr2

array([[1, 2, 8, 6],
       [9, 5, 4, 6],
       [2, 7, 1, 8]])

In [74]:
arr1-arr2

array([[ 5,  4, -5, -3],
       [-2, -2, -3,  0],
       [ 7,  0,  3,  1]])

In [76]:
np.subtract(arr1,arr2)

array([[ 5,  4, -5, -3],
       [-2, -2, -3,  0],
       [ 7,  0,  3,  1]])

In [78]:
np.multiply(arr1,arr2)

array([[ 6, 12, 24, 18],
       [63, 15,  4, 36],
       [18, 49,  4, 72]])

In [79]:
np.mod(arr1,arr2) # returns remainder

array([[0, 0, 3, 3],
       [7, 3, 1, 0],
       [1, 0, 0, 1]])

In [80]:
np.power(arr1,arr2)

array([[       6,       36,     6561,      729],
       [40353607,      243,        1,    46656],
       [      81,   823543,        4, 43046721]])

In [82]:
np.sqrt(arr1)

array([[2.44948974, 2.44948974, 1.73205081, 1.73205081],
       [2.64575131, 1.73205081, 1.        , 2.44948974],
       [3.        , 2.64575131, 2.        , 3.        ]])

In [83]:
# Numpy --> Statistical Functions 

In [84]:
arr1

array([[6, 6, 3, 3],
       [7, 3, 1, 6],
       [9, 7, 4, 9]])

In [85]:
np.mean(arr1)

5.333333333333333

In [86]:
np.median(arr1)

6.0

In [87]:
np.std(arr1)

2.4267032964268394

In [88]:
np.var(arr1)

5.888888888888888

In [89]:
np.min(arr1)

1

In [90]:
np.max(arr1)

9